// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etcgaeilcxbgbvqysjev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0Y2dhZWlsY3hiZ2J2cXlzamV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjczMzQsImV4cCI6MjA2MjkwMzMzNH0.By9P3a8NqFdNuVH_ZTl8TnXf6dZG9wgeNYCndBDq8Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);